//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3___Motel_Management_System.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThanhToanHoaDon
    {
        public string MaChiTietThanhToanHoaDon { get; set; }
        public string MaHoaDon { get; set; }
        public string NgayThanhToan { get; set; }
        public double TienThanhToan { get; set; }
        public bool TonTai { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
