//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3___Motel_Management_System.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTaiKhoan
    {
        public int MaChiTietTaiKhoan { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> MaPhongTro { get; set; }
        public Nullable<bool> TonTai { get; set; }
    
        public virtual PhongTro PhongTro { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
