//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3___Motel_Management_System.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuCoDinh
    {
        public string MaDichVuCoDinh { get; set; }
        public string MaDichVu { get; set; }
        public string MaDayTro { get; set; }
    
        public virtual DayTro DayTro { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
