//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3___Motel_Management_System.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTietThanhToanHoaDon = new HashSet<ChiTietThanhToanHoaDon>();
        }
    
        public string MaHoaDon { get; set; }
        public string MaPhongTro { get; set; }
        public string NgayTao { get; set; }
        public string ThangChiTra { get; set; }
        public bool TinhTrang { get; set; }
        public double TongTien { get; set; }
        public double DaThanhToan { get; set; }
        public Nullable<bool> TonTai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThanhToanHoaDon> ChiTietThanhToanHoaDon { get; set; }
        public virtual PhongTro PhongTro { get; set; }
    }
}
