//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3___Motel_Management_System.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaiTro
    {
        public int MaVaiTro { get; set; }
        public int MaTaiKhoan { get; set; }
        public Nullable<int> MaNguoi { get; set; }
        public string TenVaiTro { get; set; }
        public Nullable<bool> TonTai { get; set; }
    
        public virtual Nguoi Nguoi { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
